// Shared header — same course/unit/week context repeats across IPES and
// Material Base for a given week, so both editors render it identically
// instead of duplicating the fields. Source of truth today is the IPES
// payload's `introduccion` block (see domain/output/ipes.ts) — MB doesn't
// generate its own copy, so mb-week-editor.tsx fetches IPES purely to read
// this header.
//
// As of 2026-07-13 this data is split across four tiers instead of one flat
// table, per explicit instruction to "separate what is for a session, what
// is for a week, what is for a unit and what is for the course":
//   - course (curso, logro_curso): renders ONCE in iteration-weeks-view.tsx's
//     top header, plain "Label: value" text lines matching the style already
//     used for "Curso"/"Modalidad" in course-artifacts-view.tsx — no table,
//     no card, no border box.
//   - unit (unidad, logro_unidad) — UnitSummary below — and week
//     (tipos_ensenanza, tiempo_sesion_segundos) — WeekTierSummary below —
//     same plain text style, grouped under a "Unidad N" heading (sized to
//     match "Semana N") and a small "Esta semana" tier label respectively.
//     UnitSummary renders ABOVE "Semana N" and WeekTierSummary renders next
//     to it, both in iteration-weeks-view.tsx. Explicitly NOT a table or
//     card — the earlier .xlsm-table version of this was rejected twice
//     (once for being inside a carousel card, once for still reading as a
//     "card" even as a table) in favor of matching the Curso/Modalidad look.
//   - session (nombre_sesion, logro_semana, importancia — "Utilidad"):
//     genuinely varies per session, stays below as the Cabecera table (the
//     ONLY tier still shown as a table, per direct instruction to keep it
//     one — this is also the only tier with real definitions/AI-assist
//     grounding value, hence the .xlsm-table layout with defs). All three
//     Utilidad fields are editable (via Cabecera's onChangeField) when
//     rendered from ipes-week-editor.tsx, which owns this data; read-only
//     when rendered from mb-week-editor.tsx, which only holds a fetched
//     copy with no save path back to IPES.
//
// CabeceraData/cabeceraFromRawIpes still carry every field (not just
// Utilidad) because they're also sent as AI-assist context (see aiContext in
// ipes-week-editor.tsx/mb-week-editor.tsx) — only what's *rendered by this
// component* changed.

import { useState, type ReactNode } from "react"
import { ClockRegular, PinRegular, PinOffRegular } from "@fluentui/react-icons"
import AutoGrowTextarea from "../components/auto-grow-textarea"

export interface CabeceraData {
  curso: string
  logro_curso: string
  nombre_unidad: string
  logro_unidad: string
  tipos_ensenanza: string
  nombre_sesion: string
  logro_semana: string
  importancia: string
  tiempo_sesion_segundos: number  // budget for the whole week — not generated by the backend yet, see note in ipes-week-editor.tsx
}

export function cabeceraFromRawIpes(raw: any): CabeceraData {
  const intro = raw?.introduccion ?? {}
  return {
    curso:           intro.curso ?? "",
    logro_curso:     intro.logro_de_aprendizaje_curso ?? "",
    // The pipeline actually emits `unidad` (a plain number, e.g. "1") — a
    // `nombre_unidad` (descriptive name) was aspirational and never
    // generated, which silently left this field blank in production.
    // Prefer the real one, keep the old key as a fallback in case a richer
    // schema adds it later.
    nombre_unidad:   intro.unidad ?? intro.nombre_unidad ?? "",
    logro_unidad:    intro.logro_de_aprendizaje_unidad ?? "",
    tipos_ensenanza: intro.tipos_ensenanza ?? "",
    nombre_sesion:   intro.nombre_de_la_sesion ?? "",
    logro_semana:    intro.logro_de_la_semana ?? "",
    importancia:     intro.importancia_del_logro ?? "",
    tiempo_sesion_segundos: Number(intro.tiempo_sesion_segundos) || 0,
  }
}

export const CABECERA_DEFS: Record<string, string> = {
  curso:           "Nombre y código del curso al que pertenece esta semana.",
  tipos_ensenanza: "Modalidad de enseñanza de esta sesión: presencial, remoto o virtual 24/7.",
  tiempo_sesion:   "Presupuesto de tiempo total asignado a esta semana/sesión.",
  logro_curso:     "Lo que el estudiante logra al terminar todo el curso — el destino final de las 18 semanas.",
  nombre_unidad:   "La unidad (bloque de varias semanas) a la que pertenece esta semana.",
  logro_unidad:    "Lo que el estudiante logra al terminar esta unidad — más específico que el logro del curso.",
  nombre_sesion:   "El título de esta sesión — de qué trata la semana en una frase.",
  logro_semana:    "Lo que el estudiante logra al terminar esta semana en particular — el más específico de los tres logros.",
  importancia:     "Por qué este tema importa — el gancho que justifica al estudiante el esfuerzo de la semana.",
}

export function fmtHMS(totalSeconds: number): string {
  const h = Math.floor(totalSeconds / 3600)
  const m = Math.floor((totalSeconds % 3600) / 60)
  const s = Math.floor(totalSeconds % 60)
  return [h, m, s].map((n) => String(n).padStart(2, "0")).join(":")
}

// Plain "Label: value" row — same typography scale as Curso/Modalidad in
// course-artifacts-view.tsx (14px labels, no border, no background, no
// table cell) — bumped from 12.5px for legibility/consistency with that
// reference page.
function TextRow({ label, value }: { label: string; value: string }) {
  return (
    <div style={{ fontSize: 13, lineHeight: "19px", color: "var(--text-secondary)" }}>
      <span style={{ fontWeight: 700, color: "var(--text-secondary)" }}>{label}:</span> {value || "Sin definir"}
    </div>
  )
}

function TierLabel({ children }: { children: ReactNode }) {
  return (
    <div style={{ fontSize: 10, fontWeight: 800, color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: ".05em", marginBottom: 4 }}>
      {children}
    </div>
  )
}

// Thin left-border "cascade" indent — visually ties a tier to the one above
// it (Course → Unidad → Semana → Sesión), so the nesting reads as an actual
// cascade instead of a flat stack of same-looking blocks.
function CascadeLevel({ children }: { children: ReactNode }) {
  return (
    <div style={{ borderLeft: "2px solid var(--border)", paddingLeft: 12, marginBottom: 12 }}>
      {children}
    </div>
  )
}

// "Unidad N" sized to match "Semana N" in iteration-weeks-view.tsx (fontSize
// 16-17/weight 800) instead of the small uppercase TierLabel used for "Esta
// semana" — the unit is a peer heading to the week, not a minor sub-label,
// so it keeps that visual WEIGHT. Color is still var(--text-secondary)
// though, NOT black — per direct instruction, black is reserved only for
// the artifact label and "Semana N" itself; everything else (including this
// heading) uses the same muted color as Curso/Modalidad.
function UnitHeading({ children }: { children: ReactNode }) {
  return (
    <div style={{ fontSize: 16, fontWeight: 800, color: "var(--text-secondary)", marginBottom: 2 }}>
      {children}
    </div>
  )
}

export interface WeekSummaryFields {
  unidad: string
  logro_unidad: string
  tipos_ensenanza: string
  tiempo_sesion_segundos: number
}

// Plain text "Tiempo registrado: X de Y" — was a row inside the Cabecera
// table, moved here per direct instruction ("we can place those data below
// Logro de la Unidad"). Note this is genuinely SESSION data (the live total
// only exists per session, computed inside IPESWeekEditor from that
// session's own recursos/actividades) rendered inside the UNIT block for
// visibility — a deliberate exception to the tier split, not a
// reclassification. Only IPES tracks this (Material Base has no
// "tiempo de dedicación" concept), so `totalDedicacionSegundos` is only
// ever passed when viewing the IPES workspace.
function SessionTimeRow({ totalSegundos, budgetSegundos }: { totalSegundos: number; budgetSegundos: number }) {
  const over = budgetSegundos > 0 && totalSegundos > budgetSegundos
  return (
    <div style={{ fontSize: 12.5, display: "flex", alignItems: "center", gap: 4, fontWeight: over ? 700 : 400, color: over ? "var(--danger)" : "var(--text-secondary)" }}>
      <ClockRegular style={{ fontSize: 14 }} />
      <span style={{ fontWeight: 700, color: over ? "var(--danger)" : "var(--text-secondary)" }}>Tiempo registrado:</span>
      {fmtHMS(totalSegundos)} de {fmtHMS(budgetSegundos)}
      {over && " — excede el presupuesto"}
    </div>
  )
}

// Unit tier — "Unidad N" + logro de la unidad (+ optionally this session's
// live time total, see SessionTimeRow above). Rendered ABOVE "Semana N" in
// iteration-weeks-view.tsx, per direct instruction — the unit is the bigger
// grouping, so it reads first.
export function UnitSummary({ data, totalDedicacionSegundos }: { data: WeekSummaryFields; totalDedicacionSegundos?: number }) {
  const hasUnit = !!(data.unidad || data.logro_unidad)
  if (!hasUnit) return null
  return (
    <CascadeLevel>
      <UnitHeading>Unidad{data.unidad ? ` ${data.unidad}` : ""}</UnitHeading>
      {data.logro_unidad && <TextRow label="Logro de la unidad" value={data.logro_unidad} />}
      {typeof totalDedicacionSegundos === "number" && data.tiempo_sesion_segundos > 0 && (
        <SessionTimeRow totalSegundos={totalDedicacionSegundos} budgetSegundos={data.tiempo_sesion_segundos} />
      )}
    </CascadeLevel>
  )
}

// Week tier — tipos de enseñanza + tiempo de sesión (the budget, not the
// live registered total — that's SessionTimeRow above). Rendered next to
// "Semana N" in iteration-weeks-view.tsx, same plain-text style as the unit
// tier — deliberately not a table/card, see file header comment.
export function WeekTierSummary({ data }: { data: WeekSummaryFields }) {
  const hasBudget = data.tiempo_sesion_segundos > 0
  const hasWeek = !!(data.tipos_ensenanza || hasBudget)
  if (!hasWeek) return null
  return (
    <CascadeLevel>
      <TierLabel>Esta semana</TierLabel>
      <div style={{ display: "flex", gap: 20, flexWrap: "wrap" }}>
        {data.tipos_ensenanza && <TextRow label="Tipos de enseñanza" value={data.tipos_ensenanza} />}
        {hasBudget && <TextRow label="Tiempo de sesión" value={fmtHMS(data.tiempo_sesion_segundos)} />}
      </div>
    </CascadeLevel>
  )
}

type UtilidadField = "nombre_sesion" | "logro_semana" | "importancia"

// align mirrors the xlsm cell's own alignment (extracted from NuevoIPES.xlsm)
// — most value cells there are vertically centered even though left-aligned
// horizontally; a few are centered both ways. When onChange is given (and
// not readonly), renders an editable AutoGrowTextarea instead of a static
// div — all three Utilidad fields are editable now, per direct instruction
// ("all fields from Utilidad are editable"). Falls back to read-only display
// when the caller doesn't wire onChange (mb-week-editor.tsx: Material Base
// doesn't own this data — it's a read-only copy fetched from IPES for
// display, there's no save path for edits made from that view).
function Value({ value, colSpan, align, onChange }: { value: string; colSpan?: number; align?: { h?: "left" | "center"; v?: "top" | "middle" }; onChange?: (value: string) => void }) {
  const isEmpty = !value
  return (
    <td colSpan={colSpan} style={{ verticalAlign: align?.v ?? "top" }}>
      {onChange ? (
        <AutoGrowTextarea className="xlsm-textarea" style={{ textAlign: align?.h ?? "left" }} rows={1} value={value} onChange={(e) => onChange(e.target.value)} placeholder="Sin definir" />
      ) : (
        <div className={`xlsm-value-cell${isEmpty ? " empty" : ""}`} style={{ textAlign: align?.h ?? "left" }}>{value || "Sin definir"}</div>
      )}
    </td>
  )
}

// Definition lives under the field's own label, not under its value — the
// label cell is what a user reads first, so the hint belongs right there.
// Gated by showDefs (2026-07-24: hidden by default again, see
// ipes-week-editor.tsx) — this component just wasn't wired to the prop yet.
function Label({ id, showDefs, children }: { id: UtilidadField; showDefs: boolean; children: React.ReactNode }) {
  return (
    <td className="xlsm-label-cell">
      {children}
      {showDefs && CABECERA_DEFS[id] && <p className="xlsm-def" style={{ fontWeight: 400, textTransform: "none", letterSpacing: "normal" }}>{CABECERA_DEFS[id]}</p>}
    </td>
  )
}

interface Props {
  data: CabeceraData
  showDefs: boolean
  /** Wire this to make the three Utilidad fields editable; omit to keep them read-only (see Value's comment above). */
  onChangeField?: (field: UtilidadField, value: string) => void
  /** px offset to stick below when pinned — the toolbar above it. */
  top?: number
}

// Session tier ("Utilidad") — the only tier still shown as a table, per
// direct instruction. Brought back a position toggle (was removed along
// with the old resize-splitter, then asked for again) — user asked for
// "static or absolute"; implemented as static-vs-sticky instead of literal
// CSS `absolute`, because `position:absolute` needs a positioned containing
// block and would behave inconsistently depending on whether focus mode is
// on (its wrapper is position:fixed, a valid containing block) or off (no
// positioned ancestor, so it'd jump to the page root) — sticky achieves the
// actual goal (stays visible while scrolling, works the same in and out of
// focus mode) without that inconsistency. This is also THE mechanism for
// "still show the cabecera without leaving modo enfoque": pin it while
// focused and it stays docked at the top of the focus overlay's own scroll
// container as the user scrolls through the rest of the week's fields.
export function Cabecera({ data, showDefs, onChangeField, top = 49 }: Props) {
  const [sticky, setSticky] = useState(true)
  return (
    <div style={{ position: sticky ? "sticky" : "static", top: sticky ? top : undefined, zIndex: sticky ? 4 : 1, background: "var(--surface)", borderBottom: "1px solid var(--border)" }}>
      <button
        type="button"
        onClick={() => setSticky((v) => !v)}
        title={sticky ? "Cabecera fija arriba — clic para que se desplace con la página (estática)" : "Cabecera estática — clic para fijarla arriba mientras se hace scroll"}
        style={{
          position: "absolute", top: 6, right: 6, zIndex: 5,
          width: 24, height: 24, display: "flex", alignItems: "center", justifyContent: "center",
          borderRadius: 6, border: "1px solid var(--border)", background: "var(--surface)",
          color: sticky ? "var(--blue)" : "var(--text-muted)", cursor: "pointer",
        }}
      >
        {sticky ? <PinRegular style={{ fontSize: 13 }} /> : <PinOffRegular style={{ fontSize: 13 }} />}
      </button>
      <table className="xlsm-table">
        <colgroup>
          <col style={{ width: "13%" }} /><col style={{ width: "20%" }} />
          <col style={{ width: "20%" }} /><col style={{ width: "47%" }} />
        </colgroup>
        <tbody>
          <tr>
            <td rowSpan={3} className="xlsm-label-cell" style={{ background: "var(--blue-light)", color: "var(--blue-dark)", textAlign: "center", verticalAlign: "middle" }}>Utilidad</td>
            <Label id="nombre_sesion" showDefs={showDefs}>Nombre de la sesión:</Label>
            <Value value={data.nombre_sesion} colSpan={2} onChange={onChangeField && ((v) => onChangeField("nombre_sesion", v))} />
          </tr>
          <tr>
            <Label id="logro_semana" showDefs={showDefs}>Logro de la semana:</Label>
            <Value value={data.logro_semana} colSpan={2} onChange={onChangeField && ((v) => onChangeField("logro_semana", v))} />
          </tr>
          <tr>
            <Label id="importancia" showDefs={showDefs}>Importancia:</Label>
            <Value value={data.importancia} colSpan={2} onChange={onChangeField && ((v) => onChangeField("importancia", v))} />
          </tr>
        </tbody>
      </table>
    </div>
  )
}
